modLoader = "kotlinforforge"
loaderVersion = "[5,)"
license = "MIT"

[[mods]]
modId = "cobblemon_ditto_hms"
version = "${version}"
displayName = "Cobblemon Ditto HMs"
logoFile = "cobblemon-ditto-hm-logo.png"
authors = "manu"
description = '''Ditto's Pokopia HM abilities for Cobblemon. Learn abilities by interacting with Pokémon.'''

[[dependencies.cobblemon_ditto_hms]]
modId = "neoforge"
type = "required"
versionRange = "[21.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.cobblemon_ditto_hms]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.1,1.22)"
ordering = "NONE"
side = "BOTH"

[[dependencies.cobblemon_ditto_hms]]
modId = "kotlinforforge"
type = "required"
versionRange = "[5,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.cobblemon_ditto_hms]]
modId = "cobblemon"
type = "required"
versionRange = "*"
ordering = "AFTER"
side = "BOTH"
